# KYVE Chain-ID: Mainnet (kyve-1), testnet (kaon-1), or devnet (korellia-2)
chain_id: kyve-1

# KYVE Chain REST endpoint.
# Please use a trusted REST endpoint.
# Default: https://api.kyve.network
chain_rest: https://api.kyve.network

# ---
# Make sure to use the provided pools config to reproduce the same results.
# ---
pools:
  - pool_id: 0
    target_bundle_id: 259773
  - pool_id: 1
    target_bundle_id: 165755
  - pool_id: 2
    target_bundle_id: 206233
  - pool_id: 3
    target_bundle_id: 196926
  - pool_id: 5
    target_bundle_id: 147374
  - pool_id: 7
    target_bundle_id: 92882
  - pool_id: 9
    target_bundle_id: 68400